defmodule ElixirKatasWeb.ExportController do
  use ElixirKatasWeb, :controller
  alias ElixirKatas.CSV.MyParser

  def csv(conn, _params) do
    # Sample data
    headers = ["ID", "Name", "Role", "Joined Date"]
    data = [
      [1, "Alice Smith", "Engineer", "2024-01-15"],
      [2, "Bob Jones", "Designer", "2024-02-01"],
      [3, "Charlie Brown", "Manager", "2024-03-10"],
      [4, "Dana White", "Director", "2023-11-20"],
      [5, "Evan Green", "Developer", "2024-01-05"]
    ]

    csv_content = 
      [headers | data]
      |> MyParser.dump_to_iodata()

    conn
    |> put_resp_content_type("text/csv")
    |> put_resp_header("content-disposition", "attachment; filename=\"users_export.csv\"")
    |> send_resp(200, csv_content)
  end
  def pdf(conn, %{"title" => title, "body" => body}) do
    html = """
    <html>
      <head>
        <style>
          body { font-family: sans-serif; padding: 2em; }
          h1 { color: #4338ca; border-bottom: 2px solid #e5e7eb; padding-bottom: 0.5em; }
          .content { margin-top: 2em; line-height: 1.6; color: #374151; }
          .footer { margin-top: 4em; font-size: 0.8em; color: #9ca3af; border-top: 1px solid #e5e7eb; padding-top: 1em; }
        </style>
      </head>
      <body>
        <h1>#{title}</h1>
        <div class="content">
          #{Earmark.as_html!(body)}
        </div>
        <div class="footer">
          Generated by Phoenix LiveView Katas | #{Date.utc_today()}
        </div>
      </body>
    </html>
    """

    # Generate PDF
    {:ok, filename} = PdfGenerator.generate(html, page_size: "A4")
    
    # Read file content
    pdf_content = File.read!(filename)
    
    # Cleanup temp file is usually handled by OS or we should do it, 
    # but PdfGenerator typically returns a path in /tmp.
    # For robust production we'd want to ensure cleanup.

    conn
    |> put_resp_content_type("application/pdf")
    |> put_resp_header("content-disposition", "attachment; filename=\"document.pdf\"")
    |> send_resp(200, pdf_content)
  end
end
